# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: list all tasks
    cmds:
      - task --list-all
    silent: true

  prefect:server:start:
    desc: start prefect server
    cmds:
      - prefect server start

  docker:run:prefect:
    desc: running prefect with docker
    cmds:
      - docker run --name prefect -d -p 4200:4200 -v ~/.prefect:/root/.prefect prefecthq/prefect:3-latest -- prefect server start --host 0.0.0.0

  docker:start:prefect:
    desc: start prefect with docker
    cmds:
      - docker start prefect

  docker:stop:prefect:
    desc: stop prefect
    cmds:
      - docker stop prefect

  prefect:reset:
    desc: delete prefect local directory
    cmds:
      - rm -rf ~/.prefect

  prefect:server:database:reset:
    desc: delete prefect database
    cmds:
      #      - rm -rf ~/.prefect
      - prefect server database reset -y


  open:prefect:
    cmds:
      - open http://localhost:4200

  python:hello_flow:
    cmds:
      - python hello_flow.py

  python:hello_tasks:
    cmds:
      - python hello_tasks.py


  prefect:deploy:all:
    desc: deploy all defined deployment from prefect.yaml
    cmds:
      - |
        export PREFECT_API_URL=http://localhost:4200/api
        prefect deploy --all


  prefect:deploy:hello_flow:
    desc: deploy
    cmds:
      - |
        export PREFECT_API_URL=http://localhost:4200/api
        prefect deploy hello_flow.py:hello_flow -n hello-deployment

  prefect:workpool:create:my-pool:
    desc: deploy all defined deployment from prefect.yaml
    cmds:
      - |
        export PREFECT_API_URL=http://localhost:4200/api
        prefect work-pool create --type process my-pool

  prefect:worker:start:my-pool:
    desc: start worker for my opool
    cmds:
      - |
        export PREFECT_API_URL=http://localhost:4200/api
        prefect worker start --pool my-pool 
